package com.upstreak.habits.model.enums;

public enum AchievementCode {
    FIRST_HABIT_CREATED,
    FIRST_CHECKIN,
    FIRST_WEEK_COMPLETE,
    CREATE_5_HABITS,
    CREATE_10_HABITS,
    CREATE_3_CATEGORIES,
    CHECKIN_7_DAYS_ROW,
    CHECKIN_30_DAYS_ROW,
    TOTAL_CHECKINS_50,
    TOTAL_CHECKINS_100,
    FIRST_MONTH_COMPLETE,
    FIRST_3_MONTHS,
    FIRST_YEAR,
    HEALTHY_HABITS_5,
    MINDFULNESS_10,
    SLEEP_HABIT_COMPLETE_30,
    READING_10_DAYS,
    NO_SKIP_WEEK,
    TRY_NEW_HABIT
}
